# Generated by Django 5.0.1 on 2024-01-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
