# Generated by Django 5.0.1 on 2024-01-10 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_fileinfo_user_userfile_userfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='parent_folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.userfolder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userfolder'),
        ),
    ]
