# Generated by Django 5.0.1 on 2024-01-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userfile_parent_folder_userfolder_parent_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='parent_folder',
        ),
        migrations.RemoveField(
            model_name='userfolder',
            name='parent_folder',
        ),
    ]
